import classes from './products.module.css';

import Head from 'next/head';
import Footer from '../components/Footer/Footer';

import Link from 'next/link';

function index() {
  return (
    <>
    <Head>
        <title>DANH MỤC SẢN PHẨM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.webp"/>
    </Head>
      <div className={classes.header_wrapper}>
        <div className={classes.header_img}>
            <Link href='/'><a><img src='nav_img.png'/></a></Link>
        </div>
        <div className={classes.header_searchBox}>
            <input type="text" placeholder=" Search for product/ category.." />
        </div>
      </div>
      <h3 className={classes.h3}><Link href='/'><a>Trang Chủ</a></Link></h3>
      <div className={classes.common_search_options}>
        <p>HÀNG GIA DỤNG</p>
        <p>SẢN PHẨM DỆT MAY TRONG NHÀ</p>
        <p>VĂN PHÒNG PHẨM</p>
        <p>THỰC PHẨM</p>
        <p>PHỤ KIỆN TRANG ĐIỂM</p>
        <p>TRANG PHỤC NỮ</p>
        <p>TÚI VÀ GIÀY</p>
        <p>ÁO SƠ MI NAM</p>
        <p>PHỤ KIỆN TRANG TRÍ</p>
        <p>DỤNG CỤ LƯU TRỮ</p>
        <p>KỆ LƯU TRỮ</p>
        <p>DỤNG CỤ BÀN ĂN</p>
        <p>TRANG PHỤC MẶC NHÀ VÀ MẶC TRONG</p>
        <p>GIƯỜNG</p>
        <p>BÚT</p>
        <p>DỤNG CỤ NHÀ BẾP</p>
      </div>
      <div className={classes.main_content}></div>
      {/* <Footer /> */}
    </>
  )
}

export default index
