import classes from './products.module.css';
import Head from 'next/head';
import Footer from '../../components/Footer/Footer';
import Link from 'next/link';
import Product from '../../components/Product/Product';


function index(props) {
  const productsList = props.products;
  return (
    <>
    <Head>
        <title>DANH MỤC SẢN PHẨM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/main-img/logo.webp"/>
    </Head>
      <div className={classes.header_wrapper}>
        <div className={classes.header_img}>
            <Link href='/'><a><img src='/main-img/nav_img.png'/></a></Link>
        </div>
        <div className={classes.header_searchBox}>
            <input type="text" placeholder=" Search for product/ category.." />
        </div>
      </div>
      <h3 className={classes.h3}><Link href='/'><a>Trang Chủ</a></Link></h3>
      <div className={classes.common_search_options}>
        <p>HÀNG GIA DỤNG</p>
        <p>ĐỒ NỘI THẤT</p>
        <p>VĂN PHÒNG PHẨM</p>
        <p>THỰC PHẨM</p>
        <p>CHĂM SÓC SỨC KHỎE VÀ LÀM ĐẸP</p>
        <p>TRANG PHỤC NỮ</p>
        <p>TÚI VÀ GIÀY</p>
        <p>DU LỊCH</p>
        <p>TRANG PHỤC NAM</p>
        <p>DỤNG CỤ LƯU TRỮ</p>
        <p>TRANG PHỤC MẶC NHÀ VÀ MẶC TRONG</p>
        <p>DỤNG CỤ BÀN ĂN</p>
        <p>DỤNG CỤ NHÀ TẮM</p>
        <p>DỤNG CỤ NHÀ BẾP</p>
      </div>
      <h3 className={classes.h3}>TẤT CẢ SẢN PHẨM</h3>
      <div className={classes.main_content}>
        {productsList.map(product => {
          const id = product._id;
          return (
            <Link href={`http://localhost:3000/products/${id}`}>
              <div className={classes.product_item}><Product title={product.title} image={product.image} price={product.price}/></div>
            </Link>          
          )
        })}
      </div>
      <Footer />
    </>
  )
}

export default index;

export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/products");
  const products = await res.json();
  return {
    props: {
      products,
    },
  };
}

